; Nodo urbano IoT — Actividad 4
; Abrir esta carpeta (Activity-4) o el repo IoT-Labs (usa el platformio.ini raíz).

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = time
lib_deps =
    beegee-tokyo/DHT sensor library for ESPx@^1.19.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
build_src_filter = +<*>
